### PR TITLE
Move to using mainline CSSLint

### LINKED ISSUE #67: Package Loading slow
I have 124 Atom packages in Atom, and `linter-csslint` is the slowest to load out of all of them: it takes 109ms to load, even when no project is opened and so no CSS files are in the workspace.

Could `linter-csslint` possibly do something like [lazy loading](https://github.com/atom/atom/issues/2654#issuecomment-46518588)?

### LINKED ISSUE #91: Remove dependency on custom fork of CSSLint
Looks like this package depends on a custom fork of CSSLint (https://www.npmjs.com/package/atomlinter-csslint / https://github.com/AtomLinter/csslint).

This does not allow for getting newer versions of CSSLint coming from https://github.com/CSSLint/csslint

I contributed to core project - [documentation URLs](https://github.com/CSSLint/csslint/commit/ba7c0eea2d20ed89f05f92e703b54097de7601d4) to all the rules and looked to surface them in Atom linter so developers can click right from message bubbles and open detailed documentation in the browser .

### LINKED ISSUE #105: Error: Process execution timed out
I am editing a .css.liquid file and I get this error every time I save:

```
Error: Process execution timed out
    at %USER%\.atom\packages\linter-csslint\node_modules\atom-linter\lib\helpers.js:79:18
```

### LINKED ISSUE #166: Error running CSSLint
I'm using atom 1.19.
When linting any css file I get the error mentioned in the subject.
The console reads:

```
[Linter] Error running CSSLint Error: (node:75225) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: processFile(...).then is not a function
(node:75225) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at ChildProcess.<anonymous> (/Users/shillem/.atom/packages/linter-csslint/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### PR DESCRIPTION
**Pull request by Arcanemagus**
Rewrite the provider to use mainline `csslint` instead of the custom fork.

Includes:
* **BREAKING**: Disabling of linting on changes.
  * Unfortunately in over two years CSSLint has yet to merge https://github.com/CSSLint/csslint/pull/605, so for now we are stuck disabling linting on change as we have no way of sending the content to `csslint` as it changes.
* Updating to Linter v2 API.
* Allowing users to specify the path to CSSLint. Uses project local `csslint` if it exists first, and uses the bundled copy second if this option is not specified.
* Use a unique key for execution, and enforce a 30 second timeout.
  * As duplicate calls to the same key will cancel each other, there shouldn't be a need for the `disableTimeout` option any longer.
* Asyncify the specs using `jasmine-fix`.
* Update to ESLint v4.
* Update Travis CI configuration.

Fixes #67.
Fixes #91.
Fixes #105.
Closes #165.
Fixes #166.

### CODE REVIEW

File: lib/main.js [hunk 1]
```diff
@@ -28,77 +61,129 @@ export default {
...
-          return Promise.resolve([]);
+        if (!filePath || text.length === 0) {
+          // Empty or unsaved file
+          return [];
         }
-        const parameters = ['--format=json', '-'];
-        const exec = path.join(__dirname, '..', 'node_modules', 'atomlinter-csslint', 'cli.js');
+
+        const parameters = [
+          '--format=json',
```
Comment (Arcanemagus) [inline lib/main.js]: Note, requires CSSLint v1.0.0 minimum for this functionality. We might need a check for this if users start filing many support requests about broken versions.
